// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsxDV67H8myhT9QexC58rr4VNmghpREgg',
    appId: '1:796287621963:web:7e0c67b27d905bfe8c66ce',
    messagingSenderId: '796287621963',
    projectId: 'travelbudgetapp-c0173',
    authDomain: 'travelbudgetapp-c0173.firebaseapp.com',
    storageBucket: 'travelbudgetapp-c0173.appspot.com',
    measurementId: 'G-W3ZZDM9H7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9iu0zBY_y-UD16RCOXJh1yzG_oDobOKY',
    appId: '1:796287621963:android:b33b46c4be5262ae8c66ce',
    messagingSenderId: '796287621963',
    projectId: 'travelbudgetapp-c0173',
    storageBucket: 'travelbudgetapp-c0173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjdCAK_ctvcOTlulhDF3-jeoEaYpbSDoI',
    appId: '1:796287621963:ios:f70181269235613f8c66ce',
    messagingSenderId: '796287621963',
    projectId: 'travelbudgetapp-c0173',
    storageBucket: 'travelbudgetapp-c0173.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjdCAK_ctvcOTlulhDF3-jeoEaYpbSDoI',
    appId: '1:796287621963:ios:f70181269235613f8c66ce',
    messagingSenderId: '796287621963',
    projectId: 'travelbudgetapp-c0173',
    storageBucket: 'travelbudgetapp-c0173.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsxDV67H8myhT9QexC58rr4VNmghpREgg',
    appId: '1:796287621963:web:dd019cac3b2d9b058c66ce',
    messagingSenderId: '796287621963',
    projectId: 'travelbudgetapp-c0173',
    authDomain: 'travelbudgetapp-c0173.firebaseapp.com',
    storageBucket: 'travelbudgetapp-c0173.appspot.com',
    measurementId: 'G-HYJHSJHCB0',
  );
}
